Preset
khajjit/wikitext-markdown pull request #1
Opened 2018-11-19 12:00 UTC by khajjit

New user interface

2018-11-21 00:47 UTC, dhilt commented on demo/package.json
> +    "start": "cd .. && npm pack && cd demo && npm install ../wikitext-markdown-0.0.0.tgz && react-scripts start",
👍

2018-11-21 01:34 UTC, dhilt requested changes

2018-11-21 01:34 UTC, dhilt commented on demo/src/App.js
> +        <textarea style={textareaStyle} value={wikiText} onChange={this.changeWikiText.bind(this)} />
my eyes are bleeding, bind in render after all...

2018-11-21 01:34 UTC, dhilt commented on demo/src/App.js
> +        <textarea style={textareaStyle} value={markdownText} onChange={this.changeMarkdownText.bind(this)} />
again... `changeMarkdownText = (e) => { ... }` instead?

2018-11-21 01:34 UTC, dhilt commented on package.json
> +  "description": "Package for convert data from wiki-markup to markdown-markup, and back",
"A library for converting wiki to markdown and back"

2018-11-21 01:34 UTC, dhilt commented on src/index.js
> +    newText = newText.filter(line => line !== 'BLOCKQUOTE_START' && line !== 'BLOCKQUOTE_END') // TODO: remove that
todo or not todo?
btw it looks hacky...

2018-11-21 01:34 UTC, dhilt commented on src/index.js
> +      if (settings.skip.some(e => e === 'blockquote')) { // TODO: remove that
so, remove that
or remove todo

2018-11-21 01:34 UTC, dhilt commented on src/preset.js
> +function getRulesForParseWikitextToMarkdown(preset) {
need to have a white list of presets and turn this procedure into more strict form:
```
presets = [ 'presetA', 'presetB', 'default-with-html', ... ]
...
(preset) => {
  if (presets.indexOf(preset) === -1) {
    console.warn(`Invalid preset name ${preset}. Fallback to default`);
  }
  switch (preset) {
    case 'default-with-html':
      return [...defaultParseToMarkdown, ...htmlParseToMarkdown];
    default:
      return defaultParseToWiki;
  }
}
```

2018-11-21 01:34 UTC, dhilt commented on src/parse-rules/default/markdown-to-wikitext.js
> +module.exports = [
I would prefer to have an object with methods here:

```
markdownToWikitextRules = {
  ['headings']: (line) => { 
    ... 
  },

  ...

  ['italic']: (line) => { 
    ... 
  }
}

module.exports = markdownToWikitextRules;
```

So rules tokens are explicit now and could be extracted into constant enumeration and reused:

```
RULES.ITALIC = 'italic';
...
  [RULES.ITALIC]: (line) => { 
    ... 
  }
```

2018-11-21 01:34 UTC, dhilt commented on src/parse-rules/html/wikitext-to-markdown.js
> +  // htmlLink,
do we really want all these stub rules? why not to remove them?

2018-11-21 01:34 UTC, dhilt commented on package.json
>    },
need also "author", "keywords" fields to be present in package.json

2018-11-21 01:36 UTC, dhilt commented on src/preset.js
> +function getRulesForParseMarkdownToWikitext(preset) {
the same note as for `getRulesForParseWikitextToMarkdown`

2019-05-01 10:21 UTC, dyuvzhenko reviewed
Comment

2019-05-01 10:22 UTC, khajjit commented on README.md
> +
Comment 2

2019-05-01 10:22 UTC, closed without merging